L("a:link img, a:visited img")
L("{")
L("			border-style: none;")
L("}")
L("")
L("/* The only way to hide the border in NS 4.x */")
L("a img")
L("{")
L("			color: white;")
L("			background-color: white;")
L("}")
L("")
L("address")
L("{")
L("			color: gray;")
L("			background-color: white;")
L("			font-size: xx-small;")
L("			text-align: right;")
L("}")
L("")
L("body")
L("{")
L("			font-family: \"microsoft sans serif\", arial, helvetica, sans-serif;")
L("			font-size: small;")
L("}")
L("")
L("h1")
L("{")
		L("white-space: nowrap")
L("}")
L("")
L(".child-of")
L("{")
L("			font-size: medium;")
L("}")
L("")
L("table,td,th")
L("{")
L("			border-collapse: collapse;")
L("			border: 1px solid #666633;")
L("}")
L("")
L("caption,.other-caption")
L("{")
L("			text-align: left;")
L("			font-size: large;")
L("}")
L("")
L("th")
L("{")
L("			background-color: #CCCC99;")
L("			color: black;")
L("}")
L("")
L("td")
L("{")
L("			vertical-align: top;")
L("}")
L("")
L(".event")
L("{")
L("			font-weight: bold;")
L("			white-space: nowrap;")
L("}")
L("")
L(".date")
L("{")
L("			white-space: nowrap;")
L("}")
L("")
L(".place")
L("{")
L("			white-space: nowrap;")
L("}")
L("")
L(".source")
L("{")
L("			font-style: italic;")
L("}")
L("")
L(".partner")
L("{")
L("			font-size: medium;")
L("}")
L("")
L(".partner-events,.children")
L("{")
L("			margin-left: 8em;")
L("}")
L("")
L(".children-by")
L("{")
L("			font-size: small;")
L("}")
L("")
L("table.indexpage, table.indexpage td")
L("{")
L("			font-size: small;")
L("			border: 0px;")
L("			vertical-align: middle;")
L("			padding: .3em;")
L("}")
L("")
L("table.indexpage td.thru, table.indexpage td.dates")
L("{")
L("			font-size: xx-small;")
L("}")
L(".label")
L("{")
L("			color: gray;")
L("			background-color: white;")
L("			font-size: x-small;")
L("			text-align: right;")
L("			padding-right: .5em;")
L("}")
L("")
L("table.sourcepage,  table.sourcepage td")
L("{")
L("			border: 0px;")
L("}")
L("")
L(".title")
L("{")
L("			font-weight: bold;")
L("			font-style: italic;")
L("}")
L("")
L(".publ, .repo")
L("{")
L("			font-size: x-small;")
L("}")
L(".filename")
L("{")
L("			font-weight: bold;")
L("			text-transform: lowercase;")
L("}")
L("")
L(".filedesc")
L("{")
L("			margin-left: 4em;")
L("}")
