L("{\\*\\bkmkstart %id%}{\\*\\bkmkend %id%}{\\fs16 {\\b \\fs32 %name%}\\par\\par\n")
L("child of {\\b %father%} %fatherid% and {\\b %mother%} %motherid%\\par\n")
L("%events%\n")
L("\\par {\\b \\fs24 Events}\\par\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx1440 \\clNoWrap \\clvertalb \\intbl {\\b event}\\cell\n")
L("\\cellx2880 \\clNoWrap \\clvertalb \\intbl {\\b date}\\cell\n")
L("\\cellx4320 \\clNoWrap \\clvertalb \\intbl {\\b place}\\cell\n")
L("\\cellx5760 \\clNoWrap \\clvertalb \\intbl {\\b notes}\\cell\n")
L("\\cellx7200 \\clNoWrap \\clvertalb \\intbl {\\b citation}\\cell\n")
L("\\row}\n")
L("%event%\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\clvertalb \\cellx1440 \\clNoWrap \\intbl {\\b %type%}\\cell\n")
L("\\clvertalb \\cellx2880 \\clNoWrap \\intbl %date%\\cell\n")
L("\\clvertalb \\cellx4320 \\clNoWrap \\intbl %place%\\cell\n")
L("\\clvertalb \\cellx5760 \\clNoWrap \\intbl %notes%\\cell\n")
L("\\clvertalb \\cellx7200 \\clNoWrap \\intbl {\\i \\fs12 %citation%}\\cell\n")
L("\\row}\n")
L("%/event%\n")
L("%/events%\n")
L("%attributes%\n")
L("\\par\n")
L("{\\b \\fs24 Attributes}\\par\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx1440 \\clNoWrap \\intbl {\\b attribute}\\cell\n")
L("\\cellx2880 \\clNoWrap \\intbl {\\b value}\\cell\n")
L("\\cellx4320 \\clNoWrap \\intbl {\\b date}\\cell\n")
L("\\cellx5760 \\clNoWrap \\intbl {\\b place}\\cell\n")
L("\\cellx7200 \\clNoWrap \\intbl {\\b notes}\\cell\n")
L("\\cellx8640 \\clNoWrap \\intbl {\\b citation}\\cell\n")
L("\\row}\n")
L("%attribute%\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx1440 \\clNoWrap \\intbl {\\b %type%}\\cell\n")
L("\\cellx2880 \\clNoWrap \\intbl %value%\\cell\n")
L("\\cellx4320 \\clNoWrap \\intbl %date%\\cell\n")
L("\\cellx5760 \\clNoWrap \\intbl %place%\\cell\n")
L("\\cellx7200 \\clNoWrap \\intbl %notes%\\cell\n")
L("\\cellx8640 \\clNoWrap \\intbl {\\i \\fs12 %citation%}\\cell\n")
L("\\row}\n")
L("%/attribute%\n")
L("%/attributes%\n")
L("%partnerships%\n")
L("\\par\n")
L("{\\b \\fs24 Partnerships} \\par\n")
L("%partnership%\n")
L("\\par partner: {\\b %name%} %id% \\par\n")
L("%events%\n")
L("{\\b \\fs24 Events} \\par\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx1440 \\clNoWrap \\intbl {\\b event}\\cell\n")
L("\\cellx2880 \\clNoWrap \\intbl {\\b date}\\cell\n")
L("\\cellx4320 \\clNoWrap \\intbl {\\b place}\\cell\n")
L("\\cellx5760 \\clNoWrap \\intbl {\\b notes}\\cell\n")
L("\\cellx7200 \\clNoWrap \\intbl {\\b citation}\\cell\n")
L("\\row}\n")
L("%event%\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx1440 \\clNoWrap \\intbl {\\b %type%}\\cell\n")
L("\\cellx2880 \\clNoWrap \\intbl %date%\\cell\n")
L("\\cellx4320 \\clNoWrap \\intbl %place%\\cell\n")
L("\\cellx5760 \\clNoWrap \\intbl %notes%\\cell\n")
L("\\cellx7200 \\clNoWrap \\intbl {\\i \\fs12 %citation%}\\cell\n")
L("\\row}\n")
L("%/event%\n")
L("%/events%\n")
L("%children%\n")
L("\\par\n")
L("{\\b \\fs24 Children}\n")
L("\\par\n")
L("%child%\n")
L("{\\trowd \\trautofit1 \\trgaph45\n")
L("\\cellx5760 \\clNoWrap \\intbl %name% %id%\\cell\n")
L("\\row}\n")
L("%/child%\n")
L("%/children%\n")
L("%/partnership%\n")
L("%/partnerships%\n")
L("}\n")
L("\\page\n")
