//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gedtree.rc
//
#define IDR_MAINFRAME                   128
#define IDR_GEDTRETYPE                  129
#define IDR_GEDINTYPE                   130
#define IDR_GEDPDTYPE                   131
#define IDR_GEDILTYPE                   132
#define IDRC_GEDTRETYPE                 140
#define IDD_ABOUTBOX                    256
#define IDD_RELATIVES                   257
#define IDD_DATE                        258
#define IDD_ZOOM                        259
#define IDD_EVENT                       260
#define IDD_SAVECHANGES                 261
#define IDD_FIND                        262
#define IDD_CITATION                    263
#define IDD_CONFIRMDELETE               264
#define IDD_SOURCE                      265
#define IDD_SOURCES                     266
#define IDD_REPOS                       267
#define IDD_REPO                        268
#define IDD_PROGRESS                    269
#define IDD_DOCSIZE                     270
#define IDD_NAME                        271
#define IDD_NOTES                       272
#define IDD_SUBM                        273
#define IDD_SEX                         274
#define IDD_CONNECT                     275
#define IDD_UNICODE                     277
#define IDD_HOLIDAY                     278
#define IDD_SETUP                       279
#define IDD_BIRTH_CALC                  286
#define IDD_PLACE                       287
#define IDR_GRORGS                      288
#define IDR_GROGETDATA                  289
#define IDD_PWD                         290
#define IDD_REGISTER                    291
#define IDD_WEBSERVER                   292
#define IDC_SCALE                       1000
#define IDC_SPS                         1001
#define IDC_SIB                         1002
#define IDC_SIBSPS                      1003
#define IDC_CHILD                       1004
#define IDC_CHILDSPS                    1005
#define IDC_DESC                        1006
#define IDC_DESCSPS                     1007
#define IDC_FATHER                      1008
#define IDC_FATHERSIB                   1009
#define IDC_FATHERSIBSPS                1010
#define IDC_ANCMALE                     1011
#define IDC_FATHERANCSIB                1012
#define IDC_FATHERANCSIBSPS             1013
#define IDC_MOTHER                      1014
#define IDC_MOTHERSIB                   1015
#define IDC_MOTHERSIBSPS                1016
#define IDC_ANCFEMALE                   1017
#define IDC_MOTHERANCSIB                1018
#define IDC_MOTHERANCSIBSPS             1019
#define IDC_ANC                         1020
#define IDC_ANCSIB                      1021
#define IDC_ANCSIBSPS                   1022
#define IDC_DATE                        1023
#define IDC_SOURCE                      1024
#define IDC_MONTH                       1025
#define IDC_DAY                         1026
#define IDC_YEAR                        1027
#define IDC_BC                          1028
#define IDC_AD                          1029
#define IDC_GREGORIAN                   1030
#define IDC_JULIAN                      1031
#define IDC_MONTH2                      1032
#define IDC_DAY2                        1033
#define IDC_YEAR2                       1034
#define IDC_BC2                         1035
#define IDC_AD2                         1036
#define IDC_GREGORIAN2                  1037
#define IDC_JULIAN2                     1038
#define IDC_STATICAFTER                 1039
#define IDC_STATICBEFORE                1040
#define IDC_LONG                        1041
#define IDC_SHORT                       1042
#define IDC_GED                         1043
#define IDC_PHRASETEXT                  1044
#define IDC_TYPE                        1044
#define IDC_PLACE                       1045
#define IDC_STRING                      1046
#define IDC_CHANGEDATE                  1047
#define IDC_DATETYPE                    1048
#define IDC_CHANGESOURCE                1048
#define IDC_NAME                        1049
#define IDC_QUAY                        1050
#define IDC_PAGE                        1051
#define IDC_TEXT                        1052
#define IDC_CHANGEREPO                  1053
#define IDC_AUTHOR                      1054
#define IDC_TITLE                       1055
#define IDC_PUBL                        1056
#define IDC_REPO                        1057
#define IDC_DELETE                      1058
#define IDC_NEW                         1059
#define IDC_SOURCES                     1060
#define IDC_EDIT                        1061
#define IDC_REPOS                       1062
#define IDC_PROGRESS                    1063
#define IDC_MESSAGE                     1064
#define IDC_DETAIL                      1065
#define IDC_WIDTH                       1066
#define IDC_HEIGHT                      1067
#define IDC_NORMALIZE                   1068
#define IDC_FILENAME                    1069
#define IDC_ABOUT                       1070
#define IDC_ADDR                        1072
#define IDC_UNKNOWN                     1073
#define IDC_MALE                        1074
#define IDC_FEMALE                      1075
#define IDC_NOTE                        1076
#define IDC_INDI1                       1079
#define IDC_INDI0                       1080
#define IDC_SPOUSE                      1082
#define IDC_SIBLING                     1085
#define IDC_FAMILY                      1086
#define IDC_PARENT                      1088
#define IDC_EVENT                       1089
#define IDC_ASCII                       1091
#define IDC_UNICODE                     1092
#define IDC_HOLIDAY                     1093
#define IDC_ADD                         1096
#define IDC_REMOVE                      1097
#define IDC_UNINSTALL                   1098
#define IDC_YEARS                       1099
#define IDC_MONTHS                      1100
#define IDC_DAYS                        1101
#define IDC_YEARS2                      1102
#define IDC_YEARS3                      1103
#define IDC_AGE1                        1104
#define IDC_AGE2                        1105
#define IDC_AGE3                        1106
#define IDC_CENSUS_LABEL                1108
#define IDC_BIRTH                       1109
#define IDC_CENSUS_BIRTH                1110
#define IDC_DATE_IN                     1111
#define IDC_YEAROFAGE                   1113
#define IDC_OLDPWD                      1114
#define IDC_PWD1                        1115
#define IDC_PWD2                        1116
#define IDC_KEY                         1118
#define IDC_IE                          1120
#define IDC_REFRESH                     1121
#define IDC_TAB                         1122
#define IDC_PORT                        1123
#define IDC_RUNNING                     1124
#define IDC_DESCMALE                    1126
#define IDC_DESCFEMALE                  1127
#define IDC_YCHROM                      1128
#define IDC_MTDNA                       1129
#define IDD_CHOOSEFONT                  1543
#define ID_EDIT_ALIGNTOP                32771
#define ID_EDIT_CLEAN                   32772
#define ID_EDIT_SELECTANCESTORS         32773
#define ID_EDIT_DISCONNECT              32774
#define ID_EDIT_NEWINDIVIDUAL           32775
#define ID_EDIT_FINDNEXT                32776
#define ID_EDIT_RESIZEDOCUMENT          32777
#define ID_VIEW_ZOOMOUT                 32778
#define ID_VIEW_SCROLLTOSELECTION       32779
#define ID_VIEW_NOTES                   32780
#define ID_OPTIONS_FONT                 32781
#define ID_EDIT_SELECTALL               32782
#define ID_VIEW_CENSUS                  32783
#define ID_OPTIONS_SUBMITTER            32784
#define ID_EDIT_CONNECT                 32785
#define ID_VIEW_SOURCES                 32786
#define ID_VIEW_REPOSITORIES            32787
#define ID_VIEW_INDI                    32788
#define ID_VIEW_OPENPEDIGREE            32789
#define ID_VIEW_INDEXOFINDIVIDUALS      32790
#define ID_OPTIONS_UNICODE              32791
#define ID_TOOLS_HOLIDAY                32792
#define ID_VIEW_DROPLINECHART           32793
#define ID_OPTIONS_CLEANREG             32794
#define ID_FILE_SETUP                   32795
#define ID_FILE_HTML                    32796
#define ID_WEB_SITE                     32797
#define ID_BIRTH_CALC                   32798
#define ID_VIEW_PLACE                   32799
#define ID_FILE_INDEX                   32800
#define ID_OPTIONS_PAGEBREAKS           32801
#define ID_EDIT_SHOWASOF                32802
#define ID_FILE_RTF                     32803
#define ID_VIEW_ANOMALIES               32804
#define ID_FILE_REGISTER                32805
#define ID_EDIT_HIDEUNSELECTED          32806
#define ID_EDIT_SHOWALL                 32807
#define ID_FILE_SERVE                   32808
#define ID_VIEW_ZOOMNORMAL              32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        293
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1130
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
