L("<h1>%title%</h1>\n")
L("<table class=\"sourcepage\">\n")
L("<tr><td><span class=\"label\">author:</span></td><td><span class=\"author\">%author%</span></td></tr>\n")
L("<tr><td><span class=\"label\">title:</span></td><td><span class=\"title\">%title%</span></td></tr>\n")
L("<tr><td><span class=\"label\">publ.:</span></td><td><span class=\"publ\">(%publisher%)</span></td></tr>\n")
L("<tr><td><span class=\"label\">repository:</span></td><td><span class=\"repo\">%repository%</span></td></tr>\n")
L("<tr><td><span class=\"label\">address:</span></td><td><span class=\"repo\">%address%</span></td></tr>\n")
L("</table>\n")
L("<p><span class=\"label\">actual transcription and/or representation of source [with notes in brackets]:</span></p>\n")
L("<hr />\n")
L("<p>\n")
L("%text%\n")
L("</p>\n")
