---
on:
  push:
    tags:
      - "*"

jobs:
  "publish":
    runs-on: "windows-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "microsoft/setup-msbuild@v1.3"

      - name: "Build"
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release -- /p:CharacterSet=Unicode
          cpack -B ../cpack

      - uses: "softprops/action-gh-release@v1"
        with:
          tag_name: "${{ env.git_tag }}"
          files: |
            cpack/gro-*.7z
            cpack/gro-*.exe
            cpack/gro-*.tar.gz
            cpack/gro-*.zip
