---
on:
  push:
    tags:
      - "*"

jobs:
  "publish":
    runs-on: "windows-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "microsoft/setup-msbuild@v1.1.3"

      - run: "msbuild gedtree.sln -maxcpucount"

      - uses: "svenstaro/upload-release-action@v2"
        with:
          file: "Debug/GRO.exe"
          asset_name: "gro-$tag.exe"
          overwrite: true
