---
on:
  push:
    branches:
      - "master"

jobs:
  "publish":
    runs-on: "windows-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"

      - uses: "microsoft/setup-msbuild@v1.1.3"

      - run: "msbuild gedtree.sln"
